name: Deploy to Firebase Hosting

on:
  push:
    branches: [ "main" ]   # change if your default branch is different
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # OIDC
      contents: read

    env:
      PROJECT_ID: viewsurein-471013
      # If you use a specific Hosting site ID different from the default, set it:
      # FIREBASE_SITE: your-site-id

    steps:
      - uses: actions/checkout@v4

      # Auth to GCP via OIDC (no JSON keys)
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: >-
            projects/948396629418/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: github-action@viewsurein-471013.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      # Deploy static files in your repo to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: |
          if [ -n "${FIREBASE_SITE}" ]; then
            firebase target:apply hosting default "${FIREBASE_SITE}" || true
          fi
          firebase deploy --only hosting --project "${PROJECT_ID}" --non-interactive
